### ISSUE TITLE
error when using vite

### ISSUE THREAD

**Issue by aljabr** [nhedger/formkit-plugin-hybridly#5]
hi,
i got 

`[plugin:vite:import-analysis] Failed to resolve import "hybridly/vue" from "node_modules/@hedger/formkit-plugin-hybridly/dist/index.mjs". Does the file exist?`

i use laravel Jetstream 

thank you.

**Comment by nhedger** [comment]
Hi @aljabr.

Could you please tell me:

- Which version of Vite
- Which version of Hybridly
- Which version of formkit-plugin-hybridly

And I'll have a look this weekend.

**Comment by aljabr** [comment]
> Hi @aljabr.
> 
> 
> 
> Could you please tell me:
> 
> 
> 
> - Which version of Vite
> 
> - Which version of Hybridly
> 
> - Which version of formkit-plugin-hybridly
> 
> 
> 
> And I'll have a look this weekend.


Hi,

"vite": "^4.3.9",

"@hedger/formkit-plugin-hybridly": "^0.1.0-alpha.2",

I use Laravel jetstream inertia 
There's no Hybridly on my dependency


https://jetstream.laravel.com/3.x/stacks/inertia.html

**Comment by nhedger** [comment]
Oh I see. This plugin is actually made for [Hybridly](https://hybridly.dev). It does not work with Inertia.js.

**Comment by aljabr** [comment]
> Oh I see. This plugin is actually made for [Hybridly](https://hybridly.dev). It does not work with Inertia.js.


Oh,
Sorry about that 🙏🏻

**Comment by nhedger** [comment]
No problem at all. I think the plugin could easily be ported to work with Inertia. Maybe you could try to fork the project and work from there.
